### ISSUE TITLE
Photos

### ISSUE THREAD

**Issue by srobbin** [smartchicago/foodborne#21]
Photos for the About section. @RaedMan, @cgansen, @corynissen, et al, feel free to attach yours to a comment in this thread. Mine is courtesy of Mr. @danxoneil.

![srobbin_profile](https://f.cloud.github.com/assets/44719/362986/fa800450-a1f5-11e2-9ef3-a7ef65097a62.jpg)

**Comment by RaedMan** [comment]
The app has been migrated to the City of Chicago and conform to internal city policies and procedures for websites.
