### ISSUE TITLE
Update Press Inquiries Contact Person

### ISSUE THREAD

**Issue by RaedMan** [smartchicago/foodborne#67]
Under http://www.foodbornechicago.org/pages/press

Press inquiries
If you are a member of the press, and would like more information about Foodborne Chicago or an interview, please contact us at doneil@cct.org or (773) 960-6045.

Change contact person to Raed.Mansour@cityofchicago.org

**Comment by srobbin** [comment]
Done!

I removed Dan's telephone number too.
